import {execFileSync} from 'node:child_process';
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';
const root=path.resolve('dist'),context={window:{}};vm.createContext(context);for(const f of ['release-media.js','catalog-data.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context);const tracks=context.window.lotusCatalog;
assert.equal(tracks.length,26);assert.ok(!tracks.some(t=>['casual','only','runaway'].includes(t.id)));assert.equal(new Set(tracks.map(t=>t.id)).size,tracks.length);
let count=0;function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,e.name);if(e.isDirectory()){if(e.name!=='assets'&&e.name!=='vendor')walk(file)}else if(e.name.endsWith('.html')){count++;const html=fs.readFileSync(file,'utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){const raw=m[1];if(/^(?:https?:|data:|mailto:|tel:|javascript:)/.test(raw))continue;const [url]=raw.split(/[?#]/);if(!url)continue;const dest=url.startsWith('/')?path.join(root,url):path.resolve(path.dirname(file),url);assert.ok(fs.existsSync(dest),`Broken local link ${file} => ${url}`)}}}}
walk(root);for(const t of tracks){assert.ok(fs.existsSync(path.join(root,'works',t.id+'.html')));assert.ok(fs.existsSync(path.join(root,t.image)));if(t.audio.startsWith('/'))assert.ok(fs.existsSync(path.join(root,t.audio)));assert.ok(t.credits&&t.role&&t.url)}
for(const track of tracks){const html=fs.readFileSync(path.join(root,'works',track.id+'.html'),'utf8'),src=html.match(/<iframe src="([^"]+)"/)[1],url=new URL(src,'https://local.test/works/');assert.equal(url.searchParams.get('record'),track.id,`CD iframe must display ${track.id}`);assert.equal(url.searchParams.get('embed'),'1');assert.equal(url.searchParams.get('open'),'1')}
for(const file of ['interaction-sound.js','water-surface.js','preview-hooks.js','portfolio-entrances.js'])execFileSync(process.execPath,['--check',path.join(root,file)],{stdio:'pipe'});
console.log(`Verified ${count} HTML files, ${tracks.length} release routes, covers, local audio, scoped CD iframes and internal links.`);

for(const file of ['app.js','catalog-data.js','film-prologue.js','blood-ink.js','red-universe.js','release-player.js','collaborators.js','vinyl-room.js','music-signal.js','navigation.js','discography.js','release-notes.js','scroll-scenes.js','studio-cosmos.js','soundcube.js','studio-player.js','record-design.js','jewel-case.js','jewel-surface.js','record-print.js','record-shop.js','record-finishes.js','pressing-profiles.js','universe-flight.js','artist-character.js','studio-room.js','studio.js','studio-interior.js','studio-synths.js','music-cursor.js','vinyl-entry.js','studio-mv-wall.js','studio-details.js','studio-glass.js','studio-batch.js','studio-lived-in.js','record-portal.js','portfolio-pages.js','new-collaborators.js','studio-desktop.js','site-motion.js','noise-particles.js','art-type.js','studio-reference-plants.js','studio-hospitality.js','type-interactions.js'])execFileSync(process.execPath,['--check',path.join(root,file)],{stdio:'pipe'});
console.log('Interaction modules: syntax checks passed.');
