import {execFileSync} from 'node:child_process';
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';
const root=path.resolve('dist'),context={window:{}};vm.createContext(context);for(const f of ['release-media.js','catalog-data.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context);const tracks=context.window.lotusCatalog;
assert.equal(tracks.length,26);assert.equal(tracks[0].id,'lov','Every song collection must open with 1 of LOV');assert.ok(!tracks.some(t=>['casual','only','runaway'].includes(t.id)));assert.equal(new Set(tracks.map(t=>t.id)).size,tracks.length);
let count=0;function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,e.name);if(e.isDirectory()){if(e.name!=='assets'&&e.name!=='vendor')walk(file)}else if(e.name.endsWith('.html')){count++;const html=fs.readFileSync(file,'utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){const raw=m[1];if(/^(?:https?:|data:|mailto:|tel:|javascript:)/.test(raw))continue;const [url]=raw.split(/[?#]/);if(!url)continue;const dest=url.startsWith('/')?path.join(root,url):path.resolve(path.dirname(file),url);assert.ok(fs.existsSync(dest),`Broken local link ${file} => ${url}`)}}}}
walk(root);for(const t of tracks){assert.ok(fs.existsSync(path.join(root,'works',t.id+'.html')));assert.ok(fs.existsSync(path.join(root,t.image)));if(t.audio.startsWith('/'))assert.ok(fs.existsSync(path.join(root,t.audio)));assert.ok(t.credits&&t.role&&t.url)}
const films=context.window.lotusFilms,archive=fs.readFileSync(path.join(root,'films/index.html'),'utf8');assert.equal(new Set(films.map(f=>f.id)).size,films.length);assert.equal(films[0].id,'show-me-love','Every MV collection must open with Show Me Love');
const staticFilmIds=[...archive.matchAll(/<button\b[^>]*data-film="([^"]+)"/g)].map(m=>m[1]);assert.deepEqual(staticFilmIds,Array.from(films,f=>f.id),'Static and interactive MV orders must agree');assert.ok(archive.includes(`id="film-player" controls playsinline preload="metadata" poster="${films[0].image}" src="${films[0].src}"`),'Initial MV must match its first card');
const shop=fs.readFileSync(path.join(root,'works/index.html'),'utf8');assert.deepEqual([...shop.matchAll(/data-record="([^"]+)"/g)].map(m=>m[1]),Array.from(tracks,t=>t.id),'CD shelf and catalog orders must agree');assert.deepEqual([...shop.matchAll(/<a class="credit-row" href="([^"]+)\.html"/g)].map(m=>m[1]),Array.from(tracks,t=>t.id),'Credits and catalog orders must agree');
const roster=fs.readFileSync(path.join(root,'collaborators/index.html'),'utf8');
for(const [release,portrait] of [['cassette','caelan-official-portrait.webp'],['im-fine','fifteenafter-spotify-portrait.webp']]){
 const src=`/assets/artists/${portrait}`;
 assert.ok(roster.includes(`src="${src}"`),`Roster must display ${release} artist portrait`);
 assert.ok(fs.readFileSync(path.join(root,'works',`${release}.html`),'utf8').includes(`src="${src}"`),`Release detail must display ${release} artist portrait`);
}

for(const film of films){assert.ok(fs.existsSync(path.join(root,film.src)),`Missing MV ${film.id}`);const card=[...archive.matchAll(/<button\b[^>]*data-film="([^"]+)"[^>]*>/g)].find(m=>m[1]===film.id);assert.ok(card,`Missing film archive card ${film.id}`);assert.ok(card[0].includes(`data-src="${film.src}"`),`Archive must use the shared MV source for ${film.id}`);assert.ok(fs.readFileSync(path.join(root,'works',film.id+'.html'),'utf8').includes(`src="${film.src}"`),`Release detail must include ${film.id} MV`)}
for(const track of tracks){const html=fs.readFileSync(path.join(root,'works',track.id+'.html'),'utf8'),src=html.match(/<iframe src="([^"]+)"/)[1],url=new URL(src,'https://local.test/works/');assert.equal(url.searchParams.get('record'),track.id,`CD iframe must display ${track.id}`);assert.equal(url.searchParams.get('embed'),'1');assert.equal(url.searchParams.get('open'),'1')}
for(const file of ['interaction-sound.js','water-surface.js','preview-hooks.js','portfolio-entrances.js','studio-opening.js','studio-entrance-type.js','identity-score.js','media-transitions.js','media-output.js','identity-ink-flow.js','music-signal.js'])execFileSync(process.execPath,['--check',path.join(root,file)],{stdio:'pipe'});
console.log(`Verified ${count} HTML files, ${tracks.length} release routes, covers, local audio, scoped CD iframes and internal links.`);

for(const file of ['app.js','catalog-data.js','film-prologue.js','blood-ink.js','red-universe.js','release-player.js','collaborators.js','vinyl-room.js','music-signal.js','navigation.js','discography.js','release-notes.js','scroll-scenes.js','studio-cosmos.js','soundcube.js','studio-player.js','record-design.js','jewel-case.js','jewel-surface.js','record-print.js','record-shop.js','record-finishes.js','pressing-profiles.js','universe-flight.js','artist-character.js','studio-room.js','studio.js','studio-interior.js','studio-synths.js','music-cursor.js','vinyl-entry.js','studio-mv-wall.js','studio-details.js','studio-glass.js','studio-batch.js','studio-prewarm.js','studio-clay.js','studio-clay-worker.js','studio-lived-in.js','record-portal.js','portfolio-pages.js','new-collaborators.js','studio-desktop.js','site-motion.js','noise-particles.js','art-type.js','studio-reference-plants.js','studio-hospitality.js','type-interactions.js'])execFileSync(process.execPath,['--check',path.join(root,file)],{stdio:'pipe'});
console.log('Interaction modules: syntax checks passed.');
